# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d514ca293115896ce82a13383d2d5c8e69d1ef4d32528e11483dceebc6e6f171ac6a314855479f0e1ebfe2e7edd0748e19fb3a5f5af823943928576414ec1067

test:
  secret_key_base: e383c8eeb45de3fca4d498ea9f31fa409face05502e4db7e505c98a348e8228ce7ccaa2f9fee224b608fac849bb4a7fa8e0d86f3d3f1377e1e58003ac7bc1719

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
